src/account/urls.py
from django.urls import path
from account.views import (registration_view, login_view, logout_view)

urlpatterns = [ 
    path('register/', registration_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
]

src/scheduler/urls.py
from django.urls import path, re_path

from django.contrib.auth import views as auth_views

from scheduler.views import home_view

# app_name = AppName

urlpatterns = [
    path("", home_view, name="home"),
    
    # Custom password reset urls
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
]

src/scheduler_system/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('scheduler.urls')),
]

src/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.

class MyAccountManager(BaseUserManager):
    
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("User must have an email address")
        user = self.model(email=self.normalize_email(email))

        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password
            )
        
        user.is_admin= True
        user.is_staff= True
        user.is_superuser= True
        user.save(using=self._db)
        return user
    
    

class Account(AbstractBaseUser):
    email           = models.EmailField(max_length=100, verbose_name="email", unique=True)
    date_joined     = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login      = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin        = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=True)
    is_staff        = models.BooleanField(default=False)
    is_superuser    = models.BooleanField(default=False)
    first_name      = models.CharField(max_length = 150)
    last_name       = models.CharField(max_length = 150)
    
    
    USERNAME_FIELD = 'email'
    
    objects = MyAccountManager()
    
    # def __str__(self):
    #     return self.email
     
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True
    

src/scheduler/models.py
from django.db import models

from django.conf import settings

class Queue(models.Model):
    arrival_time1 = models.CharField(max_length=50)
    arrival_time2 = models.CharField(max_length=50)
    arrival_time3 = models.CharField(max_length=50)
    arrival_time4 = models.CharField(max_length=50)
    average_time = models.CharField(max_length=50)
    waiting_time = models.CharField(max_length=50)
    hospital    =  models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 

src/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from account.models import Account

# Registration form
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=100)
    password1 = forms.CharField(max_length=255, widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=255, widget=forms.PasswordInput())
    class Meta:
        
        model = Account
        fields = ("first_name", "last_name", "email", "password1", "password2")
       
       
# Login form
class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = Account
        fields = ('email', 'password') 
        
    def clean(self):
        print(self.cleaned_data)
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid email or password') 

src/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from account.forms import RegistrationForm, LoginForm

# Create your views here.

def registration_view(request):
    
    context = {}
    
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=email, password=raw_password)
            login(request, user)
            return redirect('login')
        else:
            context['registration_form'] = form
    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'account/register.html', context)


# Login view
def login_view(request):
    
    context = {}
    
    user = request.user
    if user.is_authenticated:
        return redirect("home")    
    
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            print(user)
            if user:
                login(request, user)
                return redirect("home")
    else:
        # print("InValid data")
        # print(request.POST)
        form = LoginForm()
       
    context['login_form'] = form
    return render(request, 'account/login.html', context)


# logout view
def logout_view(request):
    logout(request)
    return redirect('login')

src/scheduler/views.py
from django.shortcuts import render,redirect

from scheduler.form import QueueForm
from scheduler.regression_algorithm import reg_model
from datetime import timedelta


def home_view(request):
    
    context = {}
    # Checks if the user is login
    if not request.user.is_authenticated:
        return redirect('login')
    
    if request.POST:
        # Instantiate the form
        p_form = QueueForm(request.POST)
        # checks if the form imput is valid
        if p_form.is_valid():
            # print(p_form.cleaned_data)
            # Gets the form values
            p_arrival = p_form.cleaned_data.values()
            
            arrival_time_minute = []
            
            for t in p_arrival:
                # Split the hour and minute by :
                # mins = t.split(':')
                delta = timedelta(hours=int(t.split(':')[0]), minutes=int(t.split(':')[1])) 
                
                minutes = delta.total_seconds()/60
                # print(minutes)
                arrival_time_minute.append(minutes) 
                 
                # Gets the minute
                # arrival_time_minute.append(mins) 
                
            print(arrival_time_minute)
            
            # Linear regression model 
            prediction = reg_model(arrival_time_minute) 
            total_p_schedule = prediction['total_min']/prediction['avg_time']
            context['total_p_schedule'] = total_p_schedule
            print(total_p_schedule)
            
            wait_time = []
            
            for i in arrival_time_minute:
                # Check track the first element in the array
                if arrival_time_minute.index(i) == 0:
                    p_waiting_time = prediction['avg_time']
                    print('Patients waiting time: ', p_waiting_time)
                    wait_time.append(int(p_waiting_time))
                    
                    # Delete the first element 
                    arrival_time_minute.pop(0)
                    
                # Calculate patient waiting time 
                p_waiting_time = prediction['avg_time'] + int(i)
                print('Patients waiting time: ', int(p_waiting_time))
                wait_time.append(int(p_waiting_time))
                
            # print(wait_time)
            context['wait_time'] = wait_time
            
    else:
        p_form = QueueForm()
        context['p_form']  = p_form

    return render(request, 'scheduler/home.html', context)

src/scheduler/templates/scheduler/home.html
{% extends 'base.html' %}

{% block content %}

    <!-- Begin page content -->
    <main class="container">
        <div class="row row-cols-1 row-cols-md-1 row-cols-lg-1 mb-3 text-center">
            <div class="col">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title"><small class="text-muted fw-light">Schedule Waiting Time</small></h1>
                            
                           
                                <div class=" login-form mb-5">
                                     {% if wait_time %}
                                     
                                            {% for i in wait_time %}
                                                <div class=" w-100 alert bg-secondary text-center text-white fs-5 fw-bold">
                                                    Patient Waiting Time: {{i}} minutes
                                                </div>
                                            {% endfor %}  
                                    {% else %}
                                        <form method="POST">{% csrf_token %}

                                            <h1 class="h3 mb-2 fw-normal" style="color: #000 !important; text-align:center">Patient's Arrival Time</h1>
                                            
                                            {% comment %} {% for field in loan_form %}
                                                {{field}}
                                            {% endfor %}   {% endcomment %}
                                        
                                            
                                            <div class="row">
                                                <div class="col-md-6 mb-4">
                                                    <input type="time" name="arrival_time1"class="form-control form-control-lg"   required="" id="id_arrival_time1">                
                                                    <small><i>Arrival time of  the 1 <sup>st</sup> Patient</i></small>
                                                </div>
                                                <div class="col-md-6 mb-4">
                                                    <input type="time" name="arrival_time2" class="form-control form-control-lg" required="" id="id_arrival_time2">                
                                                    <small><i>Arrival time of  the 2 <sup>nd</sup> Patient</i></small>
                                                </div>
                                                <div class="col-md-6 mb-4">
                                                    <input type="time" name="arrival_time3" class="form-control form-control-lg"  required="" id="id_arrival_time3">
                                                    <small><i>Arrival time of  the 3 <sup>rd</sup> Patient</i></small>
                                                </div>
                                                <div class="col-md-6 mb-4">
                                                    <input type="time" name="arrival_time4" class="form-control form-control-lg" required="" id="id_arrival_time4">
                                                    <small><i>Arrival time of  the 4 <sup>th</sup> Patient</i></small>
                                                </div>
                                            </div> 
                                            <div class="container">
                                                <button type="submit" class="w-100 btn btn-outline-primary">Predict Waiting time </button>
                                            </div>
                                        </form>
                                    {% endif %}
                                    {% comment %} {% for field in registration_form %} 
                                        {% for error in field.errors %}
                                            <p style="color: red; font-size: 14px;">{{error}}</p>
                                        {% endfor %}
                                    {% endfor %} {% endcomment %}

                                </div>
                               
                        </div>
                    </div>
            </div>
        
        </div>
    </main>

{% endblock content %}

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>

{% include 'snippets/header.html' %}

    <style>
    .main-content{
      min-height: 100vh;
      height: 100%;
      margin-top: 50px;
      margin-bottom: 8px;
    }
    </style>

    
  </head>
  <body>
	<div class="container-fluid container-bg" >
    {% include 'snippets/navbar.html' %}
		<!--App contents-->
		<div class="main-content">
			{% block content %}  {% endblock content %} 
		</div>
		<!--App contents-->

		<!--App footer-->
		
	</div>
    {% include 'snippets/footer.html' %}
  </body>
</html>

src/templates/snippets/footer.html
{% load static %}
<!-- footer -->
	<div class="text-center text-black p-5">
		<p>Copyright © 2021 Scheduler. All Rights Reserved </p>		
	</div>
		<!-- //footer -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'account/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    

src/templates/snippets/header.html
{% load static %}


<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Web-based artificial intelligence system for movies recommendation. " />

<!-- custom style sheet -->
<link href="{% static 'account/css/style.css' %}" rel="stylesheet" type="text/css" />
<!-- /custom style sheet -->

<!-- bootstrap -->
<link href="{% static 'account/bootstrap/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' media="all" />
<!-- //bootstrap -->

<link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
<!-- //fonts -->

src/templates/snippets/navbar.html
    
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark bg-transparent mb-5" >
            <div class="container-fluid">
            <a class="navbar-brand text-dark text-uppercase" href="{% url 'login' %}">Scheduler</a>
            <button class="navbar-toggler bg-success" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon "></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
               
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'password_change' %}">Manage Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
                </ul>
                
            </div>
            </div>
        </nav>
    </header>